# Generated by Django 4.1.6 on 2023-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_bills_ecs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
