# Generated by Django 4.1.6 on 2023-02-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_customer_data_address_alter_customer_data_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecs_data',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='money_transfers',
            name='From_accno',
        ),
        migrations.RemoveField(
            model_name='money_transfers',
            name='To_accno',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.DeleteModel(
            name='ECS_Data',
        ),
        migrations.DeleteModel(
            name='Money_Transfers',
        ),
    ]
